import React from "react";
import { getSession } from "next-auth/react";
import Signup from "@/components/Signup";
import Head from "next/head";

const signup = () => {
  return (
    <>
      <Head>
        <title>Create account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signup />
    </>
  );
};

// === SERVER-SIDE REDIRECT IF USER IS AUTHENTICATED ===
export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}

export default signup;
